# Generated by Django 5.1 on 2024-08-29 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('location', models.TextField()),
                ('workingTime', models.IntegerField()),
                ('filed', models.CharField(max_length=64)),
                ('requirement', models.TextField()),
                ('bendfit', models.TextField()),
                ('type', models.CharField(default='open', max_length=4)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_jobs', to='registration.company')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='registration.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job')),
            ],
        ),
    ]
