# Generated by Django 5.1 on 2024-08-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_filed_job_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='bendfit',
            new_name='benefit',
        ),
    ]
