# Generated by Django 5.1 on 2024-08-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_bendfit_job_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='minute',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='second',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
