# Generated by Django 5.1 on 2024-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_hour_job_minute_job_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
